---
# Deployment parameters.
# The deployment process is divided into various stages.

# Deploy local L1.
deploy_l1: false

# Deploy zkevm contracts on L1 (and also fund accounts).
deploy_zkevm_contracts_on_l1: true

# Deploy zkevm node and cdk peripheral databases.
deploy_databases: true

# Deploy cdk central/trusted environment.
deploy_cdk_central_environment: true

# Deploy cdk/bridge infrastructure.
deploy_cdk_bridge_infra: true

# Deploy permissionless node.
deploy_zkevm_permissionless_node: false

# Deploy observability stack.
deploy_observability: true

# Deploy Blockscout stack.
deploy_l2_blockscout: true

# Deploy eth load balancer.
deploy_blutgang: false

# Apply workload to the different components of the CDK stack.
apply_workload: false

args:
  # Suffix appended to service names.
  # Note: It should be a string.
  deployment_suffix: "-001"

  # The type of data availability to use.
  # Options:
  # - 'rollup': Transaction data is stored on-chain on L1.
  # - 'cdk-validium': Transaction data is stored off-chain using the CDK DA layer and a DAC.
  # In the future, we would like to support external DA protocols such as Avail, Celestia and Near.
  data_availability_mode: rollup

  # Docker images and repositories used to spin up services.
  zkevm_prover_image: hermeznetwork/zkevm-prover:v6.0.0
  # zkevm_prover_image: hermeznetwork/zkevm-prover:v4.0.19

  zkevm_node_image: hermeznetwork/zkevm-node:v0.6.5
  cdk_node_image: 0xpolygon/cdk-validium-node:0.6.5-cdk
  # cdk_node_image: 0xpolygon/cdk-validium-node:0.5.13-cdk.3

  zkevm_da_image: 0xpolygon/cdk-data-availability:0.0.7
  # zkevm_da_image: 0xpolygon/cdk-data-availability:0.0.6

  zkevm_contracts_image: leovct/zkevm-contracts # the tag is automatically replaced by the value of /zkevm_rollup_fork_id/

  # zkevm_agglayer_image: 0xpolygon/agglayer:0.1.3
  zkevm_agglayer_image: ghcr.io/agglayer/agglayer-rs:main
  zkevm_bridge_service_image: hermeznetwork/zkevm-bridge-service:v0.4.2
  panoptichain_image: minhdvu/panoptichain:0.1.47
  zkevm_bridge_ui_image: leovct/zkevm-bridge-ui:multi-network
  zkevm_bridge_proxy_image: haproxy:2.9.7
  zkevm_sequence_sender_image: "hermeznetwork/zkevm-sequence-sender:v0.2.0-RC4"
  cdk_erigon_node_image: hermeznetwork/cdk-erigon:v1.0.9
  toolbox_image: leovct/toolbox:0.0.1
  sequencer_type: "zkevm-node"

  # Port configuration.
  zkevm_hash_db_port: 50061
  zkevm_executor_port: 50071
  zkevm_aggregator_port: 50081
  zkevm_pprof_port: 6060
  zkevm_prometheus_port: 9091
  zkevm_data_streamer_port: 6900
  zkevm_rpc_http_port: 8123
  zkevm_rpc_ws_port: 8133
  zkevm_bridge_rpc_port: 8080
  zkevm_bridge_grpc_port: 9090
  zkevm_bridge_ui_port: 80
  zkevm_agglayer_port: 4444
  zkevm_dac_port: 8484
  blockscout_public_port: 50101

  # Addresses and private keys of the different components.
  # They have been generated using the following command:
  # polycli wallet inspect --mnemonic 'lab code glass agree maid neutral vessel horror deny frequent favorite soft gate galaxy proof vintage once figure diary virtual scissors marble shrug drop' --addresses 9 | tee keys.txt | jq -r '.Addresses[] | [.ETHAddress, .HexPrivateKey] | @tsv' | awk 'BEGIN{split("sequencer,aggregator,claimtxmanager,timelock,admin,loadtest,agglayer,dac,proofsigner",roles,",")} {print "zkevm_l2_" roles[NR] "_address: \"" $1 "\""; print "zkevm_l2_" roles[NR] "_private_key: \"0x" $2 "\"\n"}'
  # polycli wallet inspect --mnemonic 'twenty garment idea impact dignity humor iron ritual remind brief fantasy calm' --addresses 9 | tee keys.txt | jq -r '.Addresses[] | [.ETHAddress, .HexPrivateKey] | @tsv' | awk 'BEGIN{split("sequencer,aggregator,claimtxmanager,timelock,admin,loadtest,agglayer,dac,proofsigner",roles,",")} {print "zkevm_l2_" roles[NR] "_address: \"" $1 "\""; print "zkevm_l2_" roles[NR] "_private_key: \"0x" $2 "\"\n"}'
  zkevm_l2_sequencer_address: "0xB737f29807Bbc845e965eA358d70df52fAE80444"
  zkevm_l2_sequencer_private_key: "0x3c0df30c0ee3b26d76f16155cce5d764afb557b73f33a66146e62ee32fc61c7f"

  zkevm_l2_aggregator_address: "0x5A4f57f45B5D7cea35607a29646fA83A317fa580"
  zkevm_l2_aggregator_private_key: "0x752c7e4197b05c36302a63459edd485246e9cbbf5d7e651db48be8268d19d316"

  zkevm_l2_claimtxmanager_address: "0x3c6a194be58a0fA2D386e9Bd5302bbfD962963eD"
  zkevm_l2_claimtxmanager_private_key: "0x3d5fa3f8c73a38258249aebdb2f4e496a13c0d1dc7b5d14bf7127af0027fc98a"

  zkevm_l2_timelock_address: "0x99681Ea78f618141f3C25cC3179aDbB38120dB24"
  zkevm_l2_timelock_private_key: "0x86d506f64c3e72a31efb8a531632b5d3a5458ec5be5153e68a9231d95f3ac97d"

  zkevm_l2_admin_address: "0x9ac8822bf20cda2B0372e1E5EA3a461FcCa9853A"
  zkevm_l2_admin_private_key: "0xcef7a4b93ac082f776502c9ab4215b8fc3be6b72d45710b3b5e34c1660770ea2"

  zkevm_l2_loadtest_address: "0xF4dAdCFE734C017E1b58e11a10bAECbd480E23f3"
  zkevm_l2_loadtest_private_key: "0xbe212ee0233bac7920e220381404a8fcb368ad50806317354135caebce9c981c"

  zkevm_l2_agglayer_address: "0x5db44121f30E76bae8fCA1B4c0D52B083ee01A4D"
  zkevm_l2_agglayer_private_key: "0x156dcfc170fd9b189774b90394b0de4d09034dd14034e73bc0f499db31636795"

  zkevm_l2_dac_address: "0x6013De700B95352e97C85E0341e1A35a659443A6"
  zkevm_l2_dac_private_key: "0x98bc1607fad34b510222bac67aaeec12cba82d056705d61749449e2aed1d5aba"

  zkevm_l2_proofsigner_address: "0x739e0B4CE3E5Ba18AE912dC0620c39bD38f11ade"
  zkevm_l2_proofsigner_private_key: "0xfb6af684875cce613ecb24fac6d3d8d7d949af651bfabd0a3b3e4eeb96c6f0dd"

  # Keystore password.
  zkevm_l2_keystore_password: pSnv6Dh5s9ahuzGzH9RoCDrKAMddaX3m

  ## L1 configuration.
  l1_chain_id: 11155111
  l1_preallocated_mnemonic: patient path quality silver ethics admit process violin dance split agree poet
  l1_funding_amount: 5ether
  l1_rpc_url: https://eth-sepolia.g.alchemy.com/v2/IbeMYSz9ndioTRFbDHBRhxq_iprUKe1A
  l1_ws_url: wss://eth-sepolia.g.alchemy.com/v2/IbeMYSz9ndioTRFbDHBRhxq_iprUKe1A
  # https://github.com/ethpandaops/ethereum-package/tree/main?tab=readme-ov-file#configuration
  l1_additional_services: [
     blockscout, # block explorer
    # dora, # beaconchain explorer
    # el_forkmon, # fork monitor tool
  ]
  l1_preset: mainnet
  l1_seconds_per_slot: 12

  ## Rollup configuration.

  # The chain id of the new rollup.
  zkevm_rollup_chain_id: 70701

  # The fork id of the new rollup. It indicates the prover (zkROM/executor) version.
  zkevm_rollup_fork_id: 9

  # The address of the rollup manager contract on L1.
  # If specified, the rollup data will be retrieved from this contract instead of using the contracts service.
  # zkevm_rollup_manager_address: ""
  # # The block number at which the rollup manager contract was deployed.
  # zkevm_rollup_manager_block_number: 0
  # # The address of the global exit root contract on L2.
  # zkevm_global_exit_root_l2_address: ""
  # # The address of the Polygon data committee contract on L1.
  # polygon_data_committee_address: ""

  polygon_zkevm_explorer: https://explorer.private/
  l1_explorer_url: https://sepolia.etherscan.io/

  # If this is true, we will automatically deploy an ERC20 contract on
  # L1 to be used at the gasTokenAddress
  zkevm_use_gas_token_contract: false

  ## Permissionless node configuration.
  trusted_sequencer_node_uri: zkevm-node-sequencer-001:6900
  zkevm_aggregator_host: zkevm-node-aggregator-001
  genesis_file: templates/permissionless-node/genesis.json

  ## Tools versions
  polycli_version: v0.1.42

  ## Workload configuration.
  workload_commands: [
    "polycli_loadtest_on_l2.sh t",  # eth transfers
    "polycli_loadtest_on_l2.sh 2",  # erc20 transfers
    "polycli_loadtest_on_l2.sh 7",  # erc721 mints
    "polycli_loadtest_on_l2.sh v3", # uniswapv3 swaps
    "polycli_rpcfuzz_on_l2.sh",     # rpc calls
    "bridge.sh", # bridge tokens l1 -> l2 and l2 -> l1
  ]

  ## ETH Load balancer configuration.
  blutgang_image: makemake1337/blutgang:0.3.5
  blutgang_rpc_port: 55555
  blutgang_admin_port: 55556

  ## Observability alerting configuration.
  # slack_alerts:
    # slack_channel: ""
    # slack_token: ""
    # mention_users: ""
